### PR TITLE
add verify sample for dotnet core v6.x

### PR DESCRIPTION
**Pull request by mickhansen**

### CODE REVIEW

**Comment by sgryt** [comment]
@mickhansen https://github.com/criipto/samples/runs/7646916990?check_suite_focus=true broken

**Comment by mickhansen** [comment]
> @mickhansen https://github.com/criipto/samples/runs/7646916990?check_suite_focus=true broken

@sgryt I honestly have no idea what those build tasks are meant to accomplish, they fail on all commits IIRC and do not run tests of any kind.

**Comment by sgryt** [comment]
`dotnet run` -> browser viser mig

image

**Comment by sgryt** [comment]
@mickhansen Files seem to be missing from repo ?

image

**Comment by mickhansen** [comment]
> @mickhansen Files seem to be missing from repo ?
> 
> image

@sgryt bootstrap files were accidently in .gitignore, added now :)

**Comment by sgryt** [comment]
1 file still seems to be missing:

image

**Comment by sgryt** [comment]
`dotnet run` -> some fiddling with localhost-TLS -> SE BankID QR works.

**Comment by mickhansen** [comment]
> 1 file still seems to be missing:
> 
> image

Hmm that one should be auto built by asp.net i believe.

**Comment by sgryt** [comment]
> > 1 file still seems to be missing:
> > image
> 
> Hmm that one should be auto built by asp.net i believe. How does it render for you currently?

image

**Comment by mickhansen** [comment]
> > > 1 file still seems to be missing:
> > > image
> > 
> > 
> > Hmm that one should be auto built by asp.net i believe. How does it render for you currently?
> 
> image

Yeah that looks "correct" ;)

**Pull request merged**
